name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1

  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: "*.pdf"
